### ISSUE TITLE
x68k2elf.py: LIBCのopendir.oで変換エラーが起きる

### ISSUE THREAD

**Issue by kg68k** [yunkya2/elf2x68k#4]
x68k2elf.pyでLIBCのlibc.aを変換しようとすると、opendir.oでエラーが発生し変換できません。

## 再現手順

[LIBC](http://retropc.net/x68000/software/develop/lib/libc1132a/)のlibc32b.tgzに入っているlibc.aを用意し、下記コマンドを実行します。
```
x68k2elf.py -v libc.a
```

または、libc.aからアーカイバでopendir.oを抽出し、下記コマンドを実行します。  
(この場合は出力ファイル名の指定が必要です)
```
x68k2elf.py -v opendir.o /dev/null
```

## ログ
```
1:0000 d000  FILE: size=1142 name=opendir
(中略)
1:0160 42ff  REFLONG: sec=0xff label=10 name=_mode2unix
1:0164 1077  DATA: b')@\x00\x10\x10+\x00\x15\xc0<\x00xO\xef\x00\x10\xb0<\x00\x08f\x06\x02l\xfeI\x00\x12J\x85g\x06\x02l\xffm\x00\x12Hk\x00\x1ea\x00\xfetXOJ\x80g\x06|I\x8d\xac\x00\x10p\x000+\x00\x18H@B@r\x002+\x00\x16&\x00\x86\x81"\x03|\x19\xec\xa9t\n\xd4\x81 \x02\xd0\x80\xd0\x82\xe7\x80\x90\x82\xe7\x80\x90\x82\xd0\x80\x90\x82$\x03BBHB\xea\x8ax\x0f\xc8\x82A\xf9'
1:01dc 4202  ADRLONG: sec=0x02 offst=0xfffffffc
1:01e0 10af  DATA: b'$\x04\xe5\x82\xd0\xb0(\x00 @ \x03B@H@|\x1f\xc0\x86A\xf0\x08\x02 \x01\xe4\x80$\x08\xd4\x80|\x03\xc2\x86f\x08|\x02\xbc\x84m\x02S\x82 \x02\xd0\x80\xd0\x82\xe7\x80"\x03|\x0b\xec\xa9|\x1f\xc2\x86\xd0\x81"\x00\xe9\x81\x92\x80\xe5\x81 \x03\xea\x88|?\xc0\x86\xd2\x80 \x01\xe9\x80\x90\x81\xe5\x80r\x1f\xc2\x83\xd2\x81\xd0\x81\xd0\xbc\xff\xff\x81p)@\x00\x14)k\x00\x1a\x00\x0cR\xab\x00: +\x00:"\x00l\x04|\x7f\xd0\x86|\x80\xc0\x86\x90\x81D\x80f.J\xab\x00:f\x04r\x01`\x06"+\x00:\xec\x81 \x01\xd0\x80\xd0\x81|\x0b\xed\xa0/\x00/+\x00>N\xb9'
1:0290 42ff  REFLONG: sec=0xff label=11 name=realloc
(中略)
1:02d4 0000  END
Traceback (most recent call last):
  File "/mnt/r/./x68k2elf.py", line 819, in <module>
    objfile(f, args.outfile)
  File "/mnt/r/./x68k2elf.py", line 411, in objfile
    f.write(e.encode())
            ^^^^^^^^^^
  File "/mnt/r/./x68k2elf.py", line 274, in encode
    r.sh.contents = r.encode(self)
                    ^^^^^^^^^^^^^^
  File "/mnt/r/./x68k2elf.py", line 211, in encode
    d += r.encode(e)
         ^^^^^^^^^^^
  File "/mnt/r/./x68k2elf.py", line 201, in encode
    return pack(self.parsestr(e), self.offset, self.info, self.addend)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: 'l' format requires -2147483648 <= number <= 2147483647
```

## 備考

多分このコマンドでエラーになっているのだと思います。
```
1:01dc 4202  ADRLONG: sec=0x02 offst=0xfffffffc
```

hlkxの[kaiseki.txt](https://github.com/kg68k/hlkx/blob/main/kaiseki.txt#L136)より:
>    42 sect.b : adr.l                                       ( dc.l  sect:adr )
>        各エリアでのアドレスをプログラム内のアドレスに変換してその値を書
>        き込みます。

LIBCのソースコードopendir.cにおける
```
static int _days_in_month[12] = {
    0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334
};
(中略)
	/* トータル日数の計算 */
	days = ((ts.tm.year + 10) * 365
		+ (_days_in_month[ts.tm.month - 1])
```
の部分でこのコマンドが生成されています。
(disで言う[参照されないラベル](https://github.com/kg68k/dis/blob/main/docs/README.txt#L1348)が、このファイルにおけるデータセクションの先頭より前を指しています)

**Comment by yunkya2** [comment]
報告ありがとうございます。
なるほど。負のオフセットが使われる場合があるのですね。
08b3567f で修正しました。
